# Generated by Django 3.2.5 on 2023-11-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_likedislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], verbose_name='Like/Dislike'),
        ),
    ]
